### ISSUE TITLE
Overflow after 5min

### ISSUE THREAD

**Issue by Valstee** [f4exb/sdrangelspectrum#2]
Hi @f4exb, 
I know that is still a work in progress but I've got this issue after 4/5min playing with sdrangelspectrum print on sdrangel (server):
`2021-08-20 10:39:49.325 (C) SampleSinkFifo::write: 99 messages dropped`
`2021-08-20 10:39:49.962 (C) SampleSinkFifo::write: overflow - dropping 1024 samples`
`2021-08-20 10:39:49.962 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`
and then the display starts to freeze and continue to print this every minute :
`2021-08-20 11:03:13.878 (C) SampleSinkFifo::write: 0 messages dropped`
`2021-08-20 11:04:18.960 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`
`2021-08-20 11:06:09.283 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`

**Comment by Valstee** [comment]
I didn't manage to reproduce the bug! Everything works again...

**Comment by Valstee** [comment]
edit: the overflow has reappeared after 25min of use !
`2021-08-20 12:03:32.380 (C) SampleSinkFifo::write: 101 messages dropped`
`2021-08-20 12:03:33.086 (C) SampleSinkFifo::write: overflow - dropping 1024 samples`
`2021-08-20 12:03:33.438 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`
`2021-08-20 12:03:36.010 (C) SampleSinkFifo::write: 390 messages dropped`
`2021-08-20 12:03:37.065 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`
`2021-08-20 12:03:37.355 (C) SampleSinkFifo::write: overflow - dropping 8192 samples`

**Comment by f4exb** [comment]
What is the sample rate and decimation?
What is the averaging mode and value for the spectrum?

Also on the spectrum display (web) what do you see here:
![Untitled](https://user-images.githubusercontent.com/6192319/130241359-ff63085b-ee1f-4eed-b8d7-2f95bc28083f.png)

**Comment by Valstee** [comment]
![image](https://user-images.githubusercontent.com/77800144/130245312-ddf0f36f-6e9a-4dc2-8608-4020c4acb081.png)
![image](https://user-images.githubusercontent.com/77800144/130245560-2230eada-2615-4555-b8b9-b9348503fcc7.png)

edit : it worked for 50min before having an overflow with this configuration

**Comment by f4exb** [comment]
This is what I suspected: this is much too fast (~465 us refresh time). You need to lower it by either taking a narrower band (increase device soft decimation) or add fixed or max average on the spectrum. You should limit the refresh rate to ~20 ms for stable operation. Websockets are not designed for high speed streaming.

**Comment by Valstee** [comment]
ok thanks for these tips, after a day of testing everything seems to work! thanks @f4exb
